I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/definitions.rpy", line 26, in script
    image albert = im.Scale("Albert.png")
  File "game/definitions.rpy", line 26, in <module>
    image albert = im.Scale("Albert.png")
TypeError: __init__() takes at least 4 arguments (2 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/definitions.rpy", line 26, in script
    image albert = im.Scale("Albert.png")
  File "C:\Users\Nitsan\Downloads\renpy-7.3.5-sdk\renpy-7.3.5-sdk\renpy\ast.py", line 1013, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Nitsan\Downloads\renpy-7.3.5-sdk\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/definitions.rpy", line 26, in <module>
    image albert = im.Scale("Albert.png")
TypeError: __init__() takes at least 4 arguments (2 given)

Windows-8-6.2.9200
Ren'Py 7.3.5.606
 1.0
Wed Nov 18 10:17:43 2020
